In [ ]:
# cross validation - primeira validação
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import datasets
from sklearn import svm

In [ ]:
iris = datasets.load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# tecnica holdout
# separa os dados em treino e teste
# separa aleatoriamente 70% dos dados para treino e 30% para teste
# o tamanho dos dados de teste é definido pelo parametro test_size

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target,test_size = 0.3)

In [ ]:
# Instancia o classificador SVM
clf = svm.SVC(gamma='auto')

In [ ]:
# treina o algoritmo e gera um modelo
clf.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
# avalia o modelo com os dados de teste
clf.score(x_test,y_test)


0.9555555555555556

In [ ]:
# a função cross_validation_score recebe por parametro o modelo
# executa a cross validation com 5 folds
scores = cross_val_score(clf, iris.data, iris.target,cv=5,scoring='accuracy')
# imprime os resultados dos folds
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
# media dos resultados
scores.mean()

0.9800000000000001

In [ ]:
# segunda validação cruzada
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_boston
from sklearn.metrics import mean_absolute_error

In [ ]:
boston = load_boston()

In [ ]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
mean_absolute_error(y_test,y_pred)

0.16207782446178076

In [ ]:
X= boston.data
Y = boston.target

In [ ]:
ml=LinearRegression()


In [ ]:
ls =cross_val_score(ml,X,Y,cv=5,scoring='neg_mean_absolute_error')
ls

array([-2.62190565, -3.90725478, -4.386606  , -5.57073637, -4.76333993])

In [ ]:
ls = -ls
ls

array([2.62190565, 3.90725478, 4.386606  , 5.57073637, 4.76333993])

In [ ]:
np.mean(ls)

4.24996854419253

In [ ]:
# terceira validação cruzada
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [ ]:
# regressão logistica
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)


0.9574074074074074

In [ ]:
# SVM
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.32407407407407407

In [ ]:
# Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)


0.9574074074074074

In [ ]:
# Kfold cross validation
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
# aplicando kfold
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)


In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))



In [ ]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [ ]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [ ]:
scores_rf

[0.9449081803005008, 0.9465776293823038, 0.9165275459098498]

In [ ]:
# cross val_score_function
from sklearn.model_selection import cross_val_score
# Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [ ]:
# svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)


array([0.38063439, 0.41068447, 0.51252087])

In [ ]:
#random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)


array([0.94490818, 0.94991653, 0.92654424])

In [ ]:
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)


0.8698324022346368

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)


0.9259869646182496

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)


0.9460024829298572

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)


0.9432278088144009

In [ ]:
# validação cruzada - 5 validação

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
     iris.data, iris.target, test_size=0.4, random_state=0)

X_train.shape, y_train.shape

((90, 4), (90,))

In [ ]:
X_test.shape, y_test.shape


((60, 4), (60,))

In [ ]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)


0.9666666666666667

In [ ]:
clf.score(X_train, y_train)


0.9888888888888889

In [ ]:
from sklearn.model_selection import cross_val_score


In [ ]:
clf = svm.SVC(kernel='linear', C=1)

scores = cross_val_score(clf, iris.data, iris.target, cv=2)

scores


array([0.98666667, 0.94666667])

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.97 (+/- 0.04)


In [ ]:
from sklearn import metrics

scores = cross_val_score(
     clf, iris.data, iris.target, cv=5, scoring='f1_macro')

scores


array([0.96658312, 1.        , 0.96658312, 0.96658312, 1.        ])

In [ ]:
from sklearn.model_selection import ShuffleSplit


In [ ]:
n_samples = iris.data.shape[0]

cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)

cross_val_score(clf, iris.data, iris.target, cv=cv)


array([0.97777778, 0.97777778, 1.        ])

In [ ]:
from sklearn.model_selection import cross_val_predict


In [ ]:
predicted = cross_val_predict(clf, iris.data, iris.target, cv=10)

predicted.shape


(150,)

In [ ]:
metrics.accuracy_score(iris.target, predicted)


0.9733333333333334

In [ ]:
from sklearn.linear_model import LassoCV


In [ ]:
# cross validation iterators
from sklearn.model_selection import KFold


In [ ]:
kf = KFold(n_splits=4, shuffle=True)

X = ["a", "b", "c", "d"]
for train, test in kf.split(X):
    print("%s %s" % (train, test))


[0 1 3] [2]
[0 2 3] [1]
[0 1 2] [3]
[1 2 3] [0]


In [ ]:
#stratification
from sklearn.model_selection import StratifiedKFold


In [ ]:
X = np.ones(10)
y = [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
skf = StratifiedKFold(n_splits=3)
for train, test in skf.split(X, y):
    print("%s %s" % (train, test))


[2 3 6 7 8 9] [0 1 4 5]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 2 4 5 6 7] [3 8 9]


In [ ]:
# Grouped data
from sklearn.model_selection import GroupKFold

X = [0.1, 0.2, 2.2, 2.4, 2.3, 4.55, 5.8, 8.8, 9, 10]
y = ["a", "b", "b", "b", "c", "c", "c", "d", "d", "d"]
groups = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3]

gkf = GroupKFold(n_splits=3)
for train, test in gkf.split(X, y, groups=groups):
    print("%s %s" % (train, test))


[0 1 2 3 4 5] [6 7 8 9]
[0 1 2 6 7 8 9] [3 4 5]
[3 4 5 6 7 8 9] [0 1 2]


In [ ]:
# time series 
from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)  

for train, test in tscv.split(X):
    print("%s %s" % (train, test))

TimeSeriesSplit(max_train_size=None, n_splits=3)
[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]


In [ ]:
# validação cruzada - 6 validação
import numpy as np
import seaborn as sns

iris = sns.load_dataset('iris')

features = np.array(iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values)
target = np.array(iris['species'].values)

iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=4)

neigh.fit(features, target)

neigh.predict([[2.3, 1.1, 3.4, 2.1]]) 

array(['versicolor'], dtype=object)

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
def k_fold_cross_validation(model, x, y, n_folds=3):
    
    kf = StratifiedKFold(n_splits=n_folds)
    
    results_accuracy = []
    
    for train, test in kf.split(x, y):
        data_train, target_train = x[train], y[train]
        data_test, target_test   = x[test], y[test]
        
        model = model.fit(data_train, target_train)
        out = model.predict(data_test)
        
        accuracy = accuracy_score(target_test, out)
        results_accuracy.append(accuracy)
        
    print('accuracy')
    print(np.average(results_accuracy))


In [ ]:
k_fold_cross_validation(model=neigh, x=features, y=target, n_folds=3)

accuracy
0.9866666666666667
